### ISSUE TITLE
Unhandled Exception error

### ISSUE THREAD

**Issue by ll3N1GmAll** [matterpreter/DefenderCheck#10]
Thanks for this excellent tool. This is such a great idea! I'm having issues using it though.
When running this against any files I get the following error: 

Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Temp\testfile.exe'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at DefenderCheck.Program.Main(String[] args)

I am running it against payloads in the same folder as the DefenderCheck.exe file; and I have used the following in user and admin priv powershell windows:

.\DefenderCheck.exe binary.exe
.\DefenderCheck.exe c:\gull\path\to\binary.exe

I get the same error no matter what file i run it against and no matter the privileges the powershell terminal is opened under. Thanks for your help with this!

**Comment by theye11owk1ng** [comment]
Having the same issue

**Comment by theye11owk1ng** [comment]
Actually nevermind - you need to create a directory - c:\temp
Then it works fine :)

**Comment by ll3N1GmAll** [comment]
Thanks for your reply. It appears to be analyzing now; but is taking quite some time. It is for an 11 KB executable. Is this normal?

**Comment by matterpreter** [comment]
Not sure. It should half split down to 1 byte and if that doesn't flag (it shouldn't), it will give you the all-clear. I would assume it is Defender acting up.

**Comment by matterpreter** [comment]
Addressed the original issue in 837d659. Please open a new issue if the analysis continues to hang.
